export const ErrorCodes = {
  INVALID_INPUT: 'INVALID_INPUT',
  MODEL_REQUEST_FAILED: 'MODEL_REQUEST_FAILED',
  MODEL_RESPONSE_INVALID: 'MODEL_RESPONSE_INVALID',
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_INPUT_INVALID: 'TOOL_INPUT_INVALID',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  WORKSPACE_PATH_DENIED: 'WORKSPACE_PATH_DENIED',
  WORKSPACE_IO_FAILED: 'WORKSPACE_IO_FAILED',
  COMMAND_TIMEOUT: 'COMMAND_TIMEOUT',
  AGENT_TIMEOUT: 'AGENT_TIMEOUT',
  AGENT_BUDGET_EXHAUSTED: 'AGENT_BUDGET_EXHAUSTED',
  SUBMISSION_MISSING: 'SUBMISSION_MISSING',
  SUBMISSION_INVALID: 'SUBMISSION_INVALID',
  VERIFIER_FAILED: 'VERIFIER_FAILED',
  VERIFIER_ERROR: 'VERIFIER_ERROR',
  WORKSPACE_SETUP_FAILED: 'WORKSPACE_SETUP_FAILED',
  INTERNAL_INVARIANT_VIOLATION: 'INTERNAL_INVARIANT_VIOLATION',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
